export const FEEDBACK_EMAIL = 'feedback@neutral.af'
export const NAME = 'Neutral.af'
export const NAME_EXTENDED = 'Neutral (as f**k)'
export const SEPARATOR = '·'
export const DEFAULT_CURRENCY = 'EUR'
