name: deploy
on: [push]

jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/zeit-now@master
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
        with:
          args: --scope neutral-af --build-env BUILD_ENV=staging

  prod:
    runs-on: ubuntu-latest
    needs: [only-master]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/zeit-now@master
        if: github.ref == 'refs/heads/master'
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
        with:
          args: --scope neutral-af --prod --build-env BUILD_ENV=prod
